#!/bin/bash
# This file was created automatically by cotor as a tool wrapper.

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

composer install --working-dir=$DIR/.composer-git-hooks --quiet
exec $DIR/.composer-git-hooks/vendor/bin/cghooks "$@"
