#!/bin/bash
# This file was created automatically by cotor as a tool wrapper.

DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

composer install --working-dir=$DIR/.php-coveralls --quiet
exec $DIR/.php-coveralls/vendor/bin/php-coveralls "$@"
